version: "3.7"
services:
  hermes-auth-1:
    image: hermes-auth:0.0.1
    container_name: hermes-auth01
    ports:
      - "10200:10200"
    networks:
      hermes-net:
  hermes-auth-2:
    image: hermes-auth:0.0.1
    container_name: hermes-auth02
    ports:
      - "10201:10200"
    networks:
      hermes-net:
networks:
  hermes-net:
    name: hermes-network
