server:
  port: 8581

spring:
  application:
    name: hermes-company
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: hermes-company
        register-health-check: true
        prefer-ip-address: true