server:
  port: 23581

spring:
  application:
    name: hermes-company
  cloud:
    consul:
      host: 192.168.1.121
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: true
        prefer-ip-address: true
        health-check-interval: 10s