spring:
  jpa:
    database: mysql
  datasource:
    url: jdbc:mysql://192.168.1.121:3306/hermes
    username: root
    password: 123456
  redis:
    host: 192.168.1.121
    port: 6379
    database: 0
    timeout: 3000