server:
  port: 8600

spring:
  application:
    name: hermes-gateway
  cloud:
    consul:
      host: 192.168.1.121
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register-health-check: true
        prefer-ip-address: true
        health-check-interval: 10s
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
