spring:
  application:
    name: hermes-gateway
  cloud:
    consul:
      host: 192.168.1.121
      port: 8500
      discovery:
        health-check-interval: 10s
        health-check-path: /actuator/health
        enabled: true
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        instance-id: ${spring.application.name}-${random.value}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: account-service
#          predicates:
#            - Path=/account-service/**
#          filter:
#            - StripPrefix=1
#          uri: lb://hermes-account
#        - id: authentication-service
#          uri: lb://hermes-authentication
#          predicates:
#            - Path=/authentication/**
server:
  port: 10000